### ISSUE TITLE
Profile selector does not work with the proxy

### ISSUE THREAD

**Issue by bbhtt** [stransky/wayland-proxy#2]
I created a flatpak package https://gitlab.com/projects261/firefox-stable-flatpak with the proxy to investigate whether it can be added to the Firefox baseapp https://github.com/flathub/org.mozilla.firefox.BaseApp and then to the official flatpak on Flathub. Mozilla builds the flatpak from binary tarballs so can't use the proxy as patch.

Running `flatpak run org.mozilla.FirefoxStable -P`, then choosing a profile and clicking OK causes Firefox to not run at all. When the connection to the proxy terminates, the process seems to exit 0 as observed with strace, so I cannot get anything out of gdb. Also it doesn't seem to attempt to kill the child Firefox process if the proxy exited due to error, so the firefox process seems to linger on in the background.

```shell
(org.mozilla.FirefoxStable:3): GLib-GObject-CRITICAL **: 09:09:29.786: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[GFX1-]: glxtest: Could not connect to wayland display, WAYLAND_DISPLAY=/run/user/1000/wayland-proxy-2
[GFX1-]: Failed to init Gtk, missing display? DISPLAY=
Redirecting call to abort() to mozalloc_abort

ExceptionHandler::GenerateDump cloned child 133
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
```

**Comment by Erick555** [comment]
Someone also [reproduced](https://bugzilla.mozilla.org/show_bug.cgi?id=1743144#c102) without flatpak.

**Comment by stransky** [comment]
Should be fixed now by patches at https://bugzilla.mozilla.org/show_bug.cgi?id=1743144.

**Comment by bbhtt** [comment]
> Should be fixed now by patches at https://bugzilla.mozilla.org/show_bug.cgi?id=1743144.

Any pointers to what patches you are referring? I bumped the commit of wayland-proxy and tested a new build, but I see still the same issue.

**Comment by stransky** [comment]
> > Should be fixed now by patches at https://bugzilla.mozilla.org/show_bug.cgi?id=1743144.
> 
> Any pointers to what patches you are referring? I bumped the commit of wayland-proxy and tested a new build, but I see still the same issue.

Use the two patches from Bug 1743144. If you still see it please run with MOZ_LOG="WidgetWayland:5" and attach the log here.
Thanks.

**Comment by bbhtt** [comment]
Aha thanks. I didn't see those above. The flatpak is built from the binary package from Mozilla.

I'll see if I can somehow do a source build.
